-- CREATE DATABASE IF NOT EXISTS acebank;
-- USE acebank;

-- Tables (IF NOT EXISTS)
CREATE TABLE IF NOT EXISTS USERS (
                                     USER_ID INT AUTO_INCREMENT PRIMARY KEY,
                                     FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    AADHAAR_NO VARCHAR(12) UNIQUE NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS ACCOUNTS (
                                        ACCOUNT_NO INT PRIMARY KEY,
                                        USER_ID INT,
                                        ACCOUNT_TYPE ENUM('SAVINGS', 'CHECKING', 'LOAN') DEFAULT 'SAVINGS',
    BALANCE DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    STATUS ENUM('ACTIVE', 'BLOCKED', 'CLOSED') DEFAULT 'ACTIVE',
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
                                            ID INT AUTO_INCREMENT PRIMARY KEY,
                                            SENDER_ACCOUNT INT NULL,   -- NULL for Deposits
                                            RECEIVER_ACCOUNT INT NULL, -- NULL for Withdrawals
                                            AMOUNT DECIMAL(15, 2) NOT NULL,
    TX_TYPE ENUM('TRANSFER', 'DEPOSIT', 'WITHDRAWAL') NOT NULL,
    REMARK VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SENDER_ACCOUNT) REFERENCES ACCOUNTS(ACCOUNT_NO)
    );

CREATE TABLE IF NOT EXISTS LOAN_REQUESTS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    LOAN_TYPE VARCHAR(50) NOT NULL,
    LOAN_AMOUNT DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Migration: add LOAN_AMOUNT column if table already existed without it
ALTER TABLE LOAN_REQUESTS ADD COLUMN LOAN_AMOUNT DECIMAL(15, 2) NOT NULL DEFAULT 0.00 AFTER LOAN_TYPE;

CREATE TABLE IF NOT EXISTS PASSWORD_RESET_OTP (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    OTP VARCHAR(6) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EXPIRES_AT TIMESTAMP NOT NULL
);